micrositeName := "Xreact"
micrositeDescription := "Reactive x React"
micrositeAuthor := "Jichao Ouyang"
micrositeHomepage := "https://xreact.oyanglul.us/"
micrositeOrganizationHomepage := "https://oyanglul.us"
micrositeTwitter := "@oyanglulu"
micrositeGithubOwner := "reactive-react"
micrositeGithubRepo := "xreact"
micrositeDocumentationUrl := "/docs"
micrositeGitterChannelUrl := "jcouyang/react-most"
enablePlugins(MicrositesPlugin)
